name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  tests:

    runs-on: ubuntu-20.04

    env:
      CC: gcc-10

      CXX: g++-10

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: external
          key: ${{ hashFiles('script/ci_install_catch.sh') }}

      - name: Install Catch2
        run: script/ci_install_catch.sh

      - name: Configure
        run: cmake -S test -B build -D CMAKE_BUILD_TYPE=Release
          -D "CMAKE_PREFIX_PATH=${PWD}/external/catch"

      - name: Build
        run: cmake --build build

      - name: Run
        working-directory: build
        run: ctest --output-on-failure
